import { Feature } from '@unoff/utils'

export const featuresScheme: Array<Feature<'TOKEN_LINT'>> = [
  // Services
  {
    name: 'TOKEN_LINT',
    description: 'Token Lint service',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'SERVICE',
    availabilityForServices: ['TOKEN_LINT'],
    proForServices: ['TOKEN_LINT'],
    availabilityForEditors: ['penpot'],
  },
  // Contexts
  {
    name: 'AUDIT_SETUP',
    description: 'Audit scope/options setup and run context',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'CONTEXT',
    availabilityForServices: ['TOKEN_LINT'],
    proForServices: ['TOKEN_LINT'],
    availabilityForEditors: ['penpot'],
  },
  {
    name: 'AUDIT_REPORT',
    description: 'Audit report and token application context',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'CONTEXT',
    availabilityForServices: ['TOKEN_LINT'],
    proForServices: ['TOKEN_LINT'],
    availabilityForEditors: ['penpot'],
  },
  // Actions
  {
    name: 'RUN_AUDIT',
    description: 'Runs a token deviation audit over the chosen scope',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    availabilityForServices: ['TOKEN_LINT'],
    proForServices: ['TOKEN_LINT'],
    availabilityForEditors: ['penpot'],
  },
  {
    name: 'APPLY_TOKEN',
    description: 'Applies a matched token to a single deviation occurrence',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    availabilityForServices: ['TOKEN_LINT'],
    proForServices: ['TOKEN_LINT'],
    availabilityForEditors: ['penpot'],
  },
  {
    name: 'APPLY_TOKEN_GROUP',
    description:
      'Applies a matched token to every occurrence in a deviation group',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    availabilityForServices: ['TOKEN_LINT'],
    proForServices: ['TOKEN_LINT'],
    availabilityForEditors: ['penpot'],
  },
  {
    name: 'APPLY_ALL_EXACT_MATCHES',
    description:
      'Applies every exact-tier match across the report in one action',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    availabilityForServices: ['TOKEN_LINT'],
    proForServices: ['TOKEN_LINT'],
    availabilityForEditors: ['penpot'],
  },
  // Shortcuts and menus
  {
    name: 'SHORTCUTS',
    description: 'Quick useful links',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'DIVISION',
    availabilityForServices: ['TOKEN_LINT'],
    proForServices: ['TOKEN_LINT'],
    availabilityForEditors: [
      'figma',
      'figjam',
      'dev',
      'dev_vscode',
      'penpot',
      'sketch',
      'framer',
      'buzz',
    ],
  },
  {
    name: 'USER',
    description: 'User menu',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'DIVISION',
    availabilityForServices: ['TOKEN_LINT'],
    proForServices: ['TOKEN_LINT'],
    availabilityForEditors: [
      'figma',
      'figjam',
      'dev',
      'dev_vscode',
      'penpot',
      'sketch',
      'framer',
      'buzz',
    ],
  },
  {
    name: 'USER_CONSENT',
    description: 'User vendors consent',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'DIVISION',
    availabilityForServices: ['TOKEN_LINT'],
    proForServices: ['TOKEN_LINT'],
    availabilityForEditors: [
      'figma',
      'figjam',
      'dev',
      'dev_vscode',
      'penpot',
      'sketch',
      'framer',
      'buzz',
    ],
  },
  {
    name: 'USER_PREFERENCES',
    description: 'User preferences settings',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'CONTEXT',
    availabilityForServices: ['TOKEN_LINT'],
    proForServices: ['TOKEN_LINT'],
    availabilityForEditors: ['figma', 'penpot', 'sketch', 'framer', 'buzz'],
  },
  {
    name: 'USER_LICENSE',
    description: 'License management module',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    availabilityForServices: ['TOKEN_LINT'],
    proForServices: ['TOKEN_LINT'],
    availabilityForEditors: [
      'figma',
      'figjam',
      'dev',
      'dev_vscode',
      'penpot',
      'sketch',
      'framer',
      'buzz',
    ],
  },
  {
    name: 'USER_LANGUAGE',
    description: 'User language settings',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'DIVISION',
    availabilityForServices: ['TOKEN_LINT'],
    proForServices: ['TOKEN_LINT'],
    availabilityForEditors: [
      'figma',
      'figjam',
      'dev',
      'dev_vscode',
      'penpot',
      'sketch',
      'framer',
      'buzz',
    ],
  },
  {
    name: 'USER_LANGUAGE_EN_US',
    description: 'English US language',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'DIVISION',
    availabilityForServices: ['TOKEN_LINT'],
    proForServices: ['TOKEN_LINT'],
    availabilityForEditors: [
      'figma',
      'figjam',
      'dev',
      'dev_vscode',
      'penpot',
      'sketch',
      'framer',
      'buzz',
    ],
  },
  {
    name: 'USER_LANGUAGE_FR_FR',
    description: 'French language',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'DIVISION',
    availabilityForServices: ['TOKEN_LINT'],
    proForServices: ['TOKEN_LINT'],
    availabilityForEditors: [
      'figma',
      'figjam',
      'dev',
      'dev_vscode',
      'penpot',
      'sketch',
      'framer',
      'buzz',
    ],
  },
  {
    name: 'USER_LANGUAGE_SUGGESTION',
    description: 'User language suggestion from browser/editor',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'DIVISION',
    availabilityForServices: ['TOKEN_LINT'],
    proForServices: ['TOKEN_LINT'],
    availabilityForEditors: [
      'figma',
      'figjam',
      'dev',
      'dev_vscode',
      'penpot',
      'sketch',
      'framer',
      'buzz',
    ],
  },
  {
    name: 'HELP_ANNOUNCEMENTS',
    description: 'Release notes',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    availabilityForServices: ['TOKEN_LINT'],
    proForServices: ['TOKEN_LINT'],
    availabilityForEditors: [
      'figma',
      'figjam',
      'dev',
      'dev_vscode',
      'penpot',
      'sketch',
      'framer',
      'buzz',
    ],
  },
  {
    name: 'HELP_ONBOARDING',
    description: 'Onboarding',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'DIVISION',
    availabilityForServices: ['TOKEN_LINT'],
    proForServices: ['TOKEN_LINT'],
    availabilityForEditors: [
      'figma',
      'figjam',
      'dev',
      'dev_vscode',
      'penpot',
      'sketch',
      'framer',
      'buzz',
    ],
  },
  {
    name: 'HELP_DOCUMENTATION',
    description: 'User documentation',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    availabilityForServices: ['TOKEN_LINT'],
    proForServices: ['TOKEN_LINT'],
    availabilityForEditors: [
      'figma',
      'figjam',
      'dev',
      'dev_vscode',
      'penpot',
      'sketch',
      'framer',
      'buzz',
    ],
  },
  {
    name: 'INVOLVE_REPOSITORY',
    description: 'Repository',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    availabilityForServices: ['TOKEN_LINT'],
    proForServices: ['TOKEN_LINT'],
    availabilityForEditors: [
      'figma',
      'figjam',
      'dev',
      'dev_vscode',
      'penpot',
      'sketch',
      'framer',
      'buzz',
    ],
  },
  {
    name: 'HELP_EMAIL',
    description: 'Email support',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    availabilityForServices: ['TOKEN_LINT'],
    proForServices: ['TOKEN_LINT'],
    availabilityForEditors: [
      'figma',
      'figjam',
      'dev',
      'dev_vscode',
      'penpot',
      'sketch',
      'framer',
      'buzz',
    ],
  },
  {
    name: 'HELP_CHAT',
    description: 'Chat support',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    availabilityForServices: ['TOKEN_LINT'],
    proForServices: ['TOKEN_LINT'],
    availabilityForEditors: [
      'figma',
      'figjam',
      'dev',
      'dev_vscode',
      'penpot',
      'sketch',
      'framer',
      'buzz',
    ],
  },
  {
    name: 'INVOLVE_FEEDBACK',
    description: 'NPS and feedback form',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    availabilityForServices: ['TOKEN_LINT'],
    proForServices: ['TOKEN_LINT'],
    availabilityForEditors: [
      'figma',
      'figjam',
      'dev',
      'dev_vscode',
      'penpot',
      'sketch',
      'framer',
      'buzz',
    ],
  },
  {
    name: 'INVOLVE_ISSUES',
    description: 'Bug reports',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    availabilityForServices: ['TOKEN_LINT'],
    proForServices: ['TOKEN_LINT'],
    availabilityForEditors: [
      'figma',
      'figjam',
      'dev',
      'dev_vscode',
      'penpot',
      'sketch',
      'framer',
      'buzz',
    ],
  },
  {
    name: 'INVOLVE_COMMUNITY',
    description: 'Community discussions',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    availabilityForServices: ['TOKEN_LINT'],
    proForServices: ['TOKEN_LINT'],
    availabilityForEditors: [
      'figma',
      'figjam',
      'dev',
      'dev_vscode',
      'penpot',
      'sketch',
      'framer',
      'buzz',
    ],
  },
  {
    name: 'INVOLVE_REQUESTS',
    description: 'Feature requests',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    availabilityForServices: ['TOKEN_LINT'],
    proForServices: ['TOKEN_LINT'],
    availabilityForEditors: [
      'figma',
      'figjam',
      'dev',
      'dev_vscode',
      'penpot',
      'sketch',
      'framer',
      'buzz',
    ],
  },
  {
    name: 'MORE_ABOUT',
    description: 'Additional information',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    availabilityForServices: ['TOKEN_LINT'],
    proForServices: ['TOKEN_LINT'],
    availabilityForEditors: [
      'figma',
      'figjam',
      'dev',
      'dev_vscode',
      'penpot',
      'sketch',
      'framer',
      'buzz',
    ],
  },
  {
    name: 'MORE_NETWORK',
    description: 'Social networks',
    isActive: false,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    availabilityForServices: ['TOKEN_LINT'],
    proForServices: ['TOKEN_LINT'],
    availabilityForEditors: [
      'figma',
      'figjam',
      'dev',
      'dev_vscode',
      'penpot',
      'sketch',
      'framer',
      'buzz',
    ],
  },
  {
    name: 'MORE_AUTHOR',
    description: 'Author page',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    availabilityForServices: ['TOKEN_LINT'],
    proForServices: ['TOKEN_LINT'],
    availabilityForEditors: [
      'figma',
      'figjam',
      'dev',
      'dev_vscode',
      'penpot',
      'sketch',
      'framer',
      'buzz',
    ],
  },
  {
    name: 'RESIZE_UI',
    description: 'Resizes the window',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    availabilityForServices: ['TOKEN_LINT'],
    proForServices: ['TOKEN_LINT'],
    availabilityForEditors: [
      'figma',
      'figjam',
      'penpot',
      'sketch',
      'framer',
      'buzz',
    ],
  },
  // External
  {
    name: 'PRO_PLAN',
    description: 'Pro plan subscription',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'ACTION',
    availabilityForServices: ['TOKEN_LINT'],
    proForServices: ['TOKEN_LINT'],
    availabilityForEditors: [
      'figma',
      'figjam',
      'dev',
      'dev_vscode',
      'penpot',
      'sketch',
      'framer',
      'buzz',
    ],
  },
  {
    name: 'NOTIFICATIONS',
    description: 'User notifications',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'DIVISION',
    availabilityForServices: ['TOKEN_LINT'],
    proForServices: ['TOKEN_LINT'],
    availabilityForEditors: [
      'figma',
      'figjam',
      'dev',
      'dev_vscode',
      'penpot',
      'sketch',
      'framer',
      'buzz',
    ],
  },
  {
    name: 'AUTHENTICATION',
    description: 'User authentication module',
    isActive: true,
    isPro: false,
    isNew: false,
    type: 'DIVISION',
    availabilityForServices: ['TOKEN_LINT'],
    proForServices: ['TOKEN_LINT'],
    availabilityForEditors: [
      'figma',
      'figjam',
      'dev',
      'dev_vscode',
      'penpot',
      'sketch',
      'framer',
      'buzz',
    ],
  },
  // Add more features as needed
]

export const doSpecificMode = (
  unactiveFeature: Array<string>,
  proFeature?: Array<string>,
  newFeature?: Array<string>
) => {
  const features = featuresScheme.map((feature) => ({ ...feature }))
  const unactiveFeatures = new Set(unactiveFeature)
  const proFeatures = new Set(proFeature)
  const newFeatures = new Set(newFeature)

  return features.map((feature) => {
    if (unactiveFeatures.has(feature.name)) feature.isActive = false
    if (proFeatures.has(feature.name)) feature.isPro = true
    if (newFeatures.has(feature.name)) feature.isNew = true

    return feature
  })
}
